### ISSUE TITLE
"window is undefined" error when using Server Sider Rendering or Next.js

### ISSUE THREAD

**Issue by rishabhgupta-dev** [refiner-io/js-client-npm#3]
While importing refiner-js package in the Server side redered application. App throws below error. 
Error :  window is undefined. 

Please provide the solution to fix it.

**Comment by benmann** [comment]
This issue is very likely expected behavior, as the client can only work client-side and Next.js doesn't alwasy automatically "know" where a loaded module belongs (fronentd/backend).

Your best option to get this to work in a Next.js application, is using a dynmic import as below.
Also check out the Next docs for reference: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

```
import dynamic from 'next/dynamic'
const Refiner = dynamic(() => import('refiner-js'), { ssr: false });
```

In general when using libraries that are client-side only, make sure to also wrap the execution in a `useEffect` hook, just like you would with any other frontend library, like analytics etc.

**Comment by chezmo** [comment]
Thanks a lot for opening the issue @rishabhgupta-dev! We've added the solution to our documentation.
https://refiner.io/docs/kb/install-client/npm-package/#Nextjs_with_Server_Side_Rendering
